name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Swift version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v --filter xAIKitTests

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:5.9-jammy
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl libcurl4-openssl-dev
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v --filter xAIKitTests

  test-docker:
    name: Test in Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t xaikit-test .
    
    - name: Run tests in Docker
      run: docker run --rm xaikit-test --help