name: DocC

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Resolve Dependencies
      run: |
        xcodebuild -resolvePackageDependencies \
          -scheme xAIKit \
          -derivedDataPath ~/Developer/Xcode/DerivedData

    - name: Build DocC
      run: |
        xcodebuild docbuild \
          -scheme xAIKit \
          -derivedDataPath ~/Developer/Xcode/DerivedData \
          -destination 'platform=macOS' \
          -parallelizeTargets \
          OTHER_DOCC_FLAGS="--emit-digest --emit-lmdb-index" \
          | xcbeautify --renderer github-actions || true
        
        echo "Build completed. Checking for archives..."
        find ~/Developer/Xcode/DerivedData -type d -name "*.doccarchive" | head -20

    - name: Process Archive
      run: |
        echo "Searching for DocC archive..."
        find ~/Developer/Xcode/DerivedData -name "*.doccarchive" -type d || true
        
        ARCHIVE_PATH=$(find ~/Developer/Xcode/DerivedData -name "xAIKit.doccarchive" -type d | head -n 1)
        
        if [ -z "$ARCHIVE_PATH" ]; then
          echo "Error: DocC archive not found!"
          exit 1
        fi
        
        echo "Archive found at: $ARCHIVE_PATH"
        
        xcrun docc process-archive transform-for-static-hosting "$ARCHIVE_PATH" \
          --output-path ./docs \
          --hosting-base-path xAIKit

    - name: Create Landing Page
      run: |
        swift Scripts/create_docs_index.swift

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4