name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-macos:
    name: Build macOS Binary
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Build Release Binary
      run: |
        swift build -c release
        cp .build/release/xai-cli ./xai-cli-macos
        chmod +x xai-cli-macos
        tar -czf xai-cli-macos.tar.gz xai-cli-macos
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: xai-cli-macos
        path: xai-cli-macos.tar.gz

  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Linux Binary in Docker
      run: |
        docker build -t xaikit:release .
        docker create --name extract xaikit:release
        docker cp extract:/usr/local/bin/xai-cli ./xai-cli-linux
        docker rm extract
        chmod +x xai-cli-linux
        tar -czf xai-cli-linux.tar.gz xai-cli-linux
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: xai-cli-linux
        path: xai-cli-linux.tar.gz

  create-release:
    name: Create GitHub Release
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        files: |
          xai-cli-macos/xai-cli-macos.tar.gz
          xai-cli-linux/xai-cli-linux.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}